### ISSUE TITLE
Step-by-step assembly instructions / video

### ISSUE THREAD

**Issue by HaleTom** [ProtofyTeam/OxyGEN#11]
I want to assemble the OxyGEN V5 but so far have the following problems:

* I don't know how many bolts to use (see #5)
* I don't know what lengths of rods to use, and where they go

I live on an island with zero ventilators, and hope to save lives.

I see the following, but it is extremely high level. 

https://github.com/ProtofyTeam/OxyGEN/blob/master/oxygenM/V5/v5%20-%20OxygenProject%205mm/Assembly_OxyGEN_V5M_EN.pdf

Could you please make complete, detailed instructions for assembly, or ideally a video?

**Comment by ap0k4** [comment]
We have added the bom and new documentation about it
