### ISSUE TITLE
Please add requirements and specifications documentation

### ISSUE THREAD

**Issue by Jaribeau** [ProtofyTeam/OxyGEN#13]
Hi - thanks for your work on this, and for making the design files readily available!

However, I can't for the life of me find any other documentation. Where are are the specifications you designed to? As a team that is spinning up resources to produce designs in Cambodia, we're vetting every project we come across. Requirements and specifications (i.e. knowing that the device was designed with proper clinical input) is by far the most important part.

Ideally they would be included right in the README, and front and centre on the website.

Thanks!

**Comment by ap0k4** [comment]
Added!
