### ISSUE TITLE
Thickness in Cam STEP files is inconsistent

### ISSUE THREAD

**Issue by greg-bakker** [ProtofyTeam/OxyGEN#15]
For the OxyGEN-IP, the thickness of the cams in the STEP files is inconsistent.  
The **Cams_v1.0\Set 1\Levas_1_1.step** file shows the thickness as **4mm**.  
The **Cams_v1.0\Set 2\Levas_1_2.step** file shows the thickness as **3mm**.  
The **Cams_v1.0\Set 3\Levas_1_3.step** shows the thickness as **4mm**.  
For reference, the **Metal Sheet\DXF\Oxygen-IP V14.4 Metal Sheet 3 mm Parts.dxf** file has one set of cams on it which would show that they are **3mm** thick.
Should the cams be **3mm** or **4mm** thick?

**Comment by ap0k4** [comment]
Hello! The thickness will depend on the material with which the cams are made, preferably if they are made of aluminum, 4mm would be better.

Thanks for the warning

**Comment by ap0k4** [comment]
Fixed!

**Comment by greg-bakker** [comment]
Thanks for fixing!  If they are made from 304 Stainless is 3mm sufficient?

**Comment by ap0k4** [comment]
yes, it would be enough 3mm for stainless

**Comment by greg-bakker** [comment]
Great!  Thanks for the reply!
