### ISSUE TITLE
OxyGEN-IP Cam Set 2 DXF filenames not all consistent with the cam they contain

### ISSUE THREAD

**Issue by greg-bakker** [ProtofyTeam/OxyGEN#16]
In the **OxygenIP_V1\Cams_v1.0** folder the DXF filenames all contain a number (65, 71, 77, 83, 89), but for **Set 2** they are not all consistent with the size of the cam in the file.  I will list them all:
**--Set 1--**
65 - XL
71 - L
77 - M
83 - S
89 - XS

**--Set 2--**
65 - XL
71 - S  _(not consistent)_
77 - M
83 - L _(not consistent)_
89 - XS

**--Set 3--**
65 - XL
71 - L
77 - M
83 - S
89 - XS

**Comment by ap0k4** [comment]
Fixed! thanks :)
