### ISSUE TITLE
How to make different I/E rate

### ISSUE THREAD

**Issue by riyanfile2** [ProtofyTeam/OxyGEN#17]
What should I do with the code, if I want to make another I/E rate. 1:5 for example. because my ventilator doesn't work well. when I use 1:2 cam, the measurement shows 2:1 :(

**Comment by ap0k4** [comment]
616/5000
Hello, what you are saying is quite strange.
- make sure the motor rotates in the correct direction
- make sure that the cam is rotating in the correct direction (that no symmetry has occurred)
- make sure that the measurement method is correct (that you are measuring the air intake and not the output, that the circuit is well closed, etc.)

If you need to calculate the cams with a different ratio, we have an article on the blog that explains it, likewise, varying the ratio would not have to solve the problem that the ratio is giving you the other way around.

https://www.oxygen.protofy.xyz/post/cam-shaft-design
