### ISSUE TITLE
Please include the quantities of materials required

### ISSUE THREAD

**Issue by dbx834** [ProtofyTeam/OxyGEN#5]
Hello...

It would help if it's included in the [list of requirements](https://github.com/ProtofyTeam/OxyGEN/blob/master/V5/Oxygen%20Maker%20V2/List_Materials_V5M.md) how many units of each item are required to create one machine.

Best
/P

**Comment by HaleTom** [comment]
Broken link above.

New link to V5 list of requirements:
https://github.com/ProtofyTeam/OxyGEN/blob/master/oxygenM/V5/v5%20-%20OxygenProject%205mm/List_Materials_V5M.md

**Comment by HaleTom** [comment]
Equivalent issue en Español:
https://github.com/ProtofyTeam/OxyGEN/issues/2
