### ISSUE TITLE
Can not open dxf files with AutoCad 2010

### ISSUE THREAD

**Issue by alanboner** [ProtofyTeam/OxyGEN#7]
AutoCad says:
Unknown value "AC1027" encountered in drawing version.
Invalid or incomplete DXF input -- drawing discarded.

**Comment by SantyG99** [comment]
Do you have the blueprints for AutoCAD? Gretting from Ecuador.

**Comment by alanboner** [comment]
Here are two AutoCAD files from latest drop.  I was able to open the DXF file with Autodesk DWG TrueView. 

 

What material will you be using? 

 

-- Alan

**Comment by alanboner** [comment]
The DWF file for the wood version is attached.

 

Does this work?

**Comment by SantyG99** [comment]
Could you send me to my email directly please i can no get any file sorry, sgomez@ciauto.ec, thank you so much
